### ISSUE TITLE
Error while importing MassMumps Solver

### ISSUE THREAD

**Issue by pranavkubc** [x94carbone/GGCE#66]
Hi,
I am trying to import the petsc interface MassMUMPS solver by following the tutorial. But it throws an error saying it cannot be imported.
I think the problem is the __init__.py file inside the petsc4py folder is empty. If we add the following line, this will resolve the error I suppose.
`from .solvers import MassSolverMUMPS`

**Comment by Chiffafox** [comment]
You are of course right, this was not added for PETSc at the same level as in other solvers. I will fix this.

**Comment by x94carbone** [comment]
I think you need an explicit import here (see the PR where we discuss). For instance, I think `from ggce.solvers import MassSolverMUMPS`. If we include this import as default in the `__init__` this will break `ggce` for anyone who does not install PETSc.
