### ISSUE TITLE
Complex to float conversion error in PETSC interface

### ISSUE THREAD

**Issue by pranavkubc** [x94carbone/GGCE#67]
Hi,
I am trying to run MassMUMPS solver on UBC Sockeye cluster. I am facing this error. I am using the pre-installed PETSC package in the cluster, all imports work fine though. 

>   
 

>  0%|          | 0/5000 [00:00<?, ?it/s]/home/kaironp1/.local/lib/python3.8/site-packages/ggce/executors/petsc4py/base.py:310: ComplexWarning: Casting complex values to real discards the imaginary part
>   self._mat_X.setValues(row_start, col_pos, val)
> 
>   0%|          | 0/5000 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "/arc/project/st-rkrems-1/pranav/polaronwk/ptest.py", line 39, in <module>
>     G = solver.greens_function(k, w, eta=0.05, pbar=True)
>   File "/home/kaironp1/.local/lib/python3.8/site-packages/ggce/executors/petsc4py/base.py", line 542, in greens_function
>     s.append(self.solve(_k, _w, eta))
>   File "/home/kaironp1/.local/lib/python3.8/site-packages/ggce/executors/petsc4py/solvers.py", line 150, in solve
>     self._scaffold(k, w, eta)
>   File "/home/kaironp1/.local/lib/python3.8/site-packages/ggce/executors/petsc4py/base.py", line 310, in _scaffold
>     self._mat_X.setValues(row_start, col_pos, val)
>   File "PETSc/Mat.pyx", line 1000, in petsc4py.PETSc.Mat.setValues
>   File "PETSc/petscmat.pxi", line 870, in petsc4py.PETSc.matsetvalues
>   File "include/arraynpy.pxi", line 155, in petsc4py.PETSc.iarray_s
>   File "include/arraynpy.pxi", line 130, in petsc4py.PETSc.iarray
> TypeError: Cannot cast array data from dtype('complex128') to dtype('float64') according to the rule 'safe'

**Comment by Chiffafox** [comment]
My guess is that the PETSc pre-installed on Sockeye probably was compiled with real number support only. I think there is an easy way to check, but I don't remember how -- try googling "check PETSc scalar type" or checking their documentation.

To compile PETSc with complex number support, you have to pass the flag "--with-scalar-type=complex" during manual `make`, or, if installing through `pip`, export the variable holding those flags,
```
export PETSC_CONFIGURE_OPTIONS="--with-scalar-type=complex --download-mumps --download-scalapack"
```

**Comment by pranavkubc** [comment]
Hi I checked using 
`from petsc4py import PETSc
print(PETSc.ScalarType)`
turns out Scalartype is float64 in my case. Thanks, I'll try to sort this out
